@ECHO OFF

SET BACKUPDIR=%1

IF NOT EXIST "%BACKUPDIR%" (
  ECHO Invalid directory: %BACKUPDIR%
  ECHO Syntax: sql-server-restore.bat ^<backup-directory^>  
  EXIT /b
)

net stop SQLServerAgent
net stop MSSQLSERVER && timeout /t 5 /nobreak >nul
net start MSSQLSERVER && timeout /t 5 /nobreak >nul

SET DBNAME=msdb
SET FILEPATH=%BACKUPDIR%\%DBNAME%.bak
sqlcmd -E -C -Q "ALTER DATABASE %DBNAME% SET SINGLE_USER WITH ROLLBACK IMMEDIATE; RESTORE DATABASE %DBNAME% FROM DISK = '%FILEPATH%' WITH RECOVERY, REPLACE; ALTER DATABASE %DBNAME% SET MULTI_USER"
ECHO.

SET DBNAME=model
SET FILEPATH=%BACKUPDIR%\%DBNAME%.bak
sqlcmd -E -C -Q "ALTER DATABASE %DBNAME% SET SINGLE_USER WITH ROLLBACK IMMEDIATE; RESTORE DATABASE %DBNAME% FROM DISK = '%FILEPATH%' WITH RECOVERY, REPLACE; ALTER DATABASE %DBNAME% SET MULTI_USER"
ECHO.

SET DBNAME=tools
SET FILEPATH=%BACKUPDIR%\%DBNAME%.bak
sqlcmd -E -C -Q "ALTER DATABASE %DBNAME% SET SINGLE_USER WITH ROLLBACK IMMEDIATE; RESTORE DATABASE %DBNAME% FROM DISK = '%FILEPATH%' WITH RECOVERY, REPLACE; ALTER DATABASE %DBNAME% SET MULTI_USER"
ECHO.

SET DBNAME=tosca_common
SET FILEPATH=%BACKUPDIR%\%DBNAME%.bak
sqlcmd -E -C -Q "ALTER DATABASE %DBNAME% SET SINGLE_USER WITH ROLLBACK IMMEDIATE; RESTORE DATABASE %DBNAME% FROM DISK = '%FILEPATH%' WITH RECOVERY, REPLACE; ALTER DATABASE %DBNAME% SET MULTI_USER"
ECHO.

SET DBNAME=tosca_test_data
SET FILEPATH=%BACKUPDIR%\%DBNAME%.bak
sqlcmd -E -C -Q "ALTER DATABASE %DBNAME% SET SINGLE_USER WITH ROLLBACK IMMEDIATE; RESTORE DATABASE %DBNAME% FROM DISK = '%FILEPATH%' WITH RECOVERY, REPLACE; ALTER DATABASE %DBNAME% SET MULTI_USER"
ECHO.

net stop MSSQLSERVER && timeout /t 5 /nobreak >nul
net start MSSQLSERVER /m && timeout /t 5 /nobreak >nul

SET DBNAME=master
SET FILEPATH=%BACKUPDIR%\%DBNAME%.bak
sqlcmd -E -C -Q "RESTORE DATABASE %DBNAME% FROM DISK = '%FILEPATH%' WITH RECOVERY, REPLACE" && timeout /t 5 /nobreak >nul
ECHO.

net stop MSSQLSERVER && timeout /t 5 /nobreak >nul
net start MSSQLSERVER && timeout /t 5 /nobreak >nul
net start SQLServerAgent
